### ISSUE TITLE
Expose support for archive store

### ISSUE THREAD

**Issue by mmastika** [honourednihilist/gradle-postgresql-embedded#1]
The plugin used [postgresql-embedded](https://github.com/yandex-qatools/postgresql-embedded/) allows the user to override the cache location of PostgreSQL so that it doesn't have to download it each time it is run.

The normal use-case for the development using external DB etc, would normally be to download the artifact once and installing it in a particular directory.

This plugin, however, does not, requiring the artifact to be downloaded each time we run the task. Exposing the option to allow user to do so would cut build time out.

**Comment by honourednihilist** [comment]
Are you sure? PostgreSQL distributive is downloaded once into home directory in my projects.

Anyway, it's a good idea to have such an option. I'll check it out.

**Comment by mmastika** [comment]
The use case is more for a build server where the tools are usually pre-installed and the build is a clean checkout type of build as oppose to an incremental build.

**Comment by honourednihilist** [comment]
@mmastika it's done. Give it a try.
